# VM_PUBLIC_IP is injected by the pipeline from the epicbook-secrets variable group
[web]
<VM_PUBLIC_IP>

[web:vars]
ansible_user=azureuser
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3

